version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
