[tool.poetry]
name = "paramview"
version = "0.1.1"
description = "GUI for viewing the contents of a ParamDB database."
authors = ["Alex Hadley <alexhad6@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/PainterQubits/paramview"
include = ["paramview/static/**/*"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.3"
flask-socketio = "^5.3.3"
eventlet = "^0.33.3"
watchdog = "^3.0.0"
paramdb = "^0.5.0"

[tool.poetry.group.dev.dependencies]
sqlalchemy = "^2.0.11"
pytest = "^7.3.1"
mypy = "^1.2.0"
flake8 = "^6.0.0"
pylint = "^2.17.2"
black = "^23.3.0"

[tool.poetry.scripts]
paramview = "paramview._cli:main"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
filterwarnings = ["ignore::DeprecationWarning:eventlet.support.greenlets"]

[tool.pylint.basic]
good-names-rgxs = ["^[a-z][a-z0-9]?$"]

[tool.pylint.messages_control]
disable = ["too-few-public-methods"]

[tool.mypy]
strict = true

[[tool.poetry.source]]
name = "paramdb"
url = "https://painterqubits.github.io/paramdb/releases"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
