[tool.poetry]
name = "paramview"
version = "0.1.0"
description = "GUI for viewing the contents of a ParamDB database."
authors = ["Alex Hadley <alexhad6@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/PainterQubits/paramview"

[tool.poetry.dependencies]
python = "^3.10"
paramdb = "^0.4.0"
astropy = {version = "^5.2.2", optional = true}

[tool.poetry.extras]
astropy = ["astropy"]

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
pylint = "^2.17.1"
mypy = "^1.1.1"
black = "^23.3.0"

[[tool.poetry.source]]
name = "paramdb"
url = "https://painterqubits.github.io/paramdb/releases"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
