name: Set up backend

runs:
  using: composite
  steps:
    - name: Install Poetry
      run: pipx install poetry==1.4.2

    - name: Set up Python with Poetry cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: poetry

    - name: Install backend dependencies
      run: poetry install
