name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "[Backend] Set up"
        uses: ./.github/actions/set-up-backend

      - name: "[Backend] Check formatting (Black)"
        run: poetry run black paramview tests --check

      - name: "[Backend] Lint"
        run: |
          poetry run flake8 paramview tests
          poetry run pylint paramview tests

      - name: "[Backend] Mypy cache"
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            mypy-${{ runner.os }}-

      - name: "[Backend] Type check"
        run: poetry run mypy paramview tests

      - name: "[Backend] Test"
        run: poetry run pytest

      - name: "[Frontend] Set up"
        uses: ./.github/actions/set-up-frontend

      - name: "[Frontend] Lint"
        working-directory: frontend
        run: yarn lint

      - name: "[Frontend] Test"
        working-directory: frontend
        run: yarn test:unit

      - name: "[E2E] Build"
        run: make frontend

      - name: "[E2E] Start backend server"
        working-directory: frontend
        run: yarn backend start &

      - name: "[E2E] Start frontend server"
        working-directory: frontend
        run: yarn preview &

      - name: "[E2E] Test"
        working-directory: frontend
        run: yarn test:e2e
