name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.7.1"
  PYTHON_VERSION: "3.9"
  PACKAGE_NAME: "paramview"

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python with Poetry cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Check Formatting (Black)
        run: poetry run black ${{ env.PACKAGE_NAME }} tests --check

      - name: Lint (Flake8)
        run: poetry run flake8 ${{ env.PACKAGE_NAME }} tests

      - name: Lint (Pylint)
        run: poetry run pylint ${{ env.PACKAGE_NAME }} tests

      - name: Mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ github.sha }}
          restore-keys: |
            mypy-${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-

      - name: Type Check (Mypy)
        run: poetry run mypy ${{ env.PACKAGE_NAME }} tests

      - name: Test (Pytest)
        run: poetry run pytest tests/unit

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable Yarn
        run: corepack enable

      - name: Install Node.js dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Set up Python with Poetry cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable Yarn
        run: corepack enable

      - name: Install Node.js dependencies
        run: yarn

      - name: Install Playwright browsers
        run: poetry run playwright install chromium

      - name: Build frontend
        run: yarn build

      - name: Start E2E server
        run: poetry run python tests/e2e/start_server.py &

      - name: Ensure E2E server is up
        run: yarn wait-on http://127.0.0.1:5051 -t 1000

      - name: E2E tests
        run: poetry run pytest tests/e2e

      - name: Upload failure traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-failure-traces
          path: test-results
