name: Deploy to GitHub Pages

on: workflow_dispatch

env:
  PARAMVIEW_VERSION: "0.2.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up backend
        uses: ./.github/actions/set-up-backend

      - name: Set up frontend
        uses: ./.github/actions/set-up-frontend

      - name: Build package
        run: make

      - name: Create _site/releases/index.html
        run: |
          mkdir _site
          mkdir _site/releases
          echo '<!DOCTYPE html>
          <html>
            <body>
              <a href="paramview/">paramview</a>
            </body>
          </html>' > _site/releases/index.html

      - name: Create _site/releases/paramview/index.html
        run: |
          mkdir _site/releases/paramview
          echo '<!DOCTYPE html>
          <html>
            <body>
              <a href="paramview-${{ env.PARAMVIEW_VERSION }}-py3-none-any.whl">
                paramview-${{ env.PARAMVIEW_VERSION }}-py3-none-any.whl
              </a>
              <a href="paramview-${{ env.PARAMVIEW_VERSION }}.tar.gz">paramview-${{ env.PARAMVIEW_VERSION }}.tar.gz</a>
            </body>
          </html>' > _site/releases/paramview/index.html

      - name: Move package files into _site/releases/paramview
        run: mv dist/* _site/releases/paramview

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
